[all:vars]
ansible_connection=network_cli
ansible_network_os=ios
ansible_user=admin
ansible_password=admin
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostKeyAlgorithms=+ssh-rsa'

[routers]
isp ansible_host=172.20.20.11
hq-edge1 ansible_host=172.20.20.12
hq-edge2 ansible_host=172.20.20.13
br-edge ansible_host=172.20.20.14

[switches]
hq-core1 ansible_host=172.20.20.21
hq-core2 ansible_host=172.20.20.22
